// ============================================================
// data.js — ALL subject content lives here. Nothing else does.
// Penetration Testing curriculum, bilingual EN + عربي.
// ============================================================

export const GAME = {
  title: { en: "Cyber Range: Operation Zero-Day", ar: "نطاق التدريب: عملية اليوم صفر" },
  passMark: 0.6,
};

// XP thresholds -> rank names
export const RANKS = [
  { xp: 0,   name: "Trainee",  ar: "متدرّب" },
  { xp: 120, name: "Junior",   ar: "مبتدئ" },
  { xp: 300, name: "Analyst",  ar: "محلل" },
  { xp: 520, name: "Pro Pentester", ar: "مختبِر اختراق محترف" },
  { xp: 800, name: "Red Team Lead", ar: "قائد الفريق الأحمر" },
];

// Scope boundary — going outside = ethics violation
export const SCOPE = { radius: 155, penalty: 15 };

// Five districts = the five phases of a penetration test
export const DISTRICTS = [
  { id:"recon", order:1, color:0x2ee6a6, center:{x:-95,z:-95}, radius:34,
    name:{ en:"Recon Ridge", ar:"مرتفع الاستطلاع" },
    phase:{ en:"Phase 1 — Reconnaissance", ar:"المرحلة 1 — الاستطلاع" },
    intro:{ en:"Gather intel on the target — legally and quietly.",
            ar:"اجمع المعلومات عن الهدف — بشكل قانوني وهادئ." } },
  { id:"scan", order:2, color:0x4da6ff, center:{x:-40,z:35}, radius:34,
    name:{ en:"Scanner Bay", ar:"خليج الفحص" },
    phase:{ en:"Phase 2 — Scanning & Enumeration", ar:"المرحلة 2 — الفحص والتعداد" },
    intro:{ en:"Map live hosts, open ports and services.",
            ar:"ارسم خريطة الأجهزة والمنافذ والخدمات المفتوحة." } },
  { id:"access", order:3, color:0xffd166, center:{x:35,z:-25}, radius:36,
    name:{ en:"Breach Plaza", ar:"ساحة الاختراق" },
    phase:{ en:"Phase 3 — Gaining Access", ar:"المرحلة 3 — الحصول على الوصول" },
    intro:{ en:"Exploit web vulnerabilities to get a foothold.",
            ar:"استغل ثغرات الويب للحصول على موطئ قدم." } },
  { id:"persist", order:4, color:0xff9f43, center:{x:95,z:55}, radius:32,
    name:{ en:"Persistence Point", ar:"نقطة الثبات" },
    phase:{ en:"Phase 4 — Maintaining Access", ar:"المرحلة 4 — الحفاظ على الوصول" },
    intro:{ en:"Understand persistence and privilege escalation.",
            ar:"افهم آليات الثبات وتصعيد الصلاحيات." } },
  { id:"report", order:5, color:0xff5470, center:{x:105,z:-85}, radius:32,
    name:{ en:"Report HQ", ar:"مقر التقارير" },
    phase:{ en:"Phase 5 — Reporting", ar:"المرحلة 5 — إعداد التقارير" },
    intro:{ en:"Document findings, rate risk, recommend fixes.",
            ar:"وثّق النتائج، قيّم المخاطر، واقترح الإصلاحات." } },
];

// Discovery nodes. Each = a concept + a question. pos is world XZ.
export const NODES = [
  // ---------- PHASE 1: RECON ----------
  { id:"scope-auth", district:"recon", pos:{x:-110,z:-110}, xp:30,
    title:{ en:"Rules of Engagement & Authorization", ar:"قواعد الاشتباك والتصريح" },
    tag:{ en:"Ethics · Legal", ar:"أخلاقيات · قانوني" },
    card:{ en:"Before ANY testing you need written authorization defining scope, targets, timing and limits. Testing without permission is a crime, not hacking.",
           ar:"قبل أي اختبار تحتاج إلى تصريح مكتوب يحدد النطاق والأهداف والتوقيت والحدود. الاختبار بدون إذن جريمة وليس اختراقًا." },
    q:{ question:{ en:"What must you have before starting a pentest?", ar:"ما الذي يجب أن تمتلكه قبل بدء الاختبار؟" },
        options:[ {en:"Written authorization defining scope", ar:"تصريح مكتوب يحدد النطاق"},
                  {en:"A fast internet connection", ar:"اتصال إنترنت سريع"},
                  {en:"The target's Wi-Fi password", ar:"كلمة مرور واي فاي الهدف"},
                  {en:"Nothing, just start", ar:"لا شيء، ابدأ فقط"} ],
        answer:0,
        explain:{ en:"Authorization + defined scope is the #1 rule. No permission = illegal.",
                  ar:"التصريح وتحديد النطاق هما القاعدة الأولى. لا إذن = غير قانوني." } } },
  { id:"osint", district:"recon", pos:{x:-80,z:-95}, xp:25,
    title:{ en:"OSINT & Footprinting", ar:"الاستخبارات المفتوحة والبصمة" },
    tag:{ en:"Passive Recon", ar:"استطلاع سلبي" },
    card:{ en:"OSINT collects public info — domains, emails, employees, leaked data — without touching the target's systems. It shapes your whole attack plan.",
           ar:"تجمع OSINT المعلومات العامة — النطاقات والإيميلات والموظفين والبيانات المسربة — دون لمس أنظمة الهدف. وهي تشكّل خطة الهجوم كلها." },
    q:{ question:{ en:"OSINT is best described as…", ar:"أفضل وصف لـ OSINT هو…" },
        options:[ {en:"Collecting publicly available information", ar:"جمع المعلومات المتاحة علنًا"},
                  {en:"Brute-forcing passwords", ar:"تخمين كلمات المرور بالقوة"},
                  {en:"Installing malware", ar:"تثبيت برمجية خبيثة"},
                  {en:"Encrypting files", ar:"تشفير الملفات"} ],
        answer:0,
        explain:{ en:"OSINT = Open-Source Intelligence: public, passive, no direct contact.",
                  ar:"OSINT = استخبارات المصادر المفتوحة: علنية، سلبية، دون تواصل مباشر." } } },
  { id:"active-passive", district:"recon", pos:{x:-105,z:-72}, xp:25,
    title:{ en:"Passive vs Active Recon", ar:"الاستطلاع السلبي مقابل النشط" },
    tag:{ en:"Recon Types", ar:"أنواع الاستطلاع" },
    card:{ en:"Passive recon never interacts with the target (e.g. WHOIS, Google). Active recon touches it (e.g. pinging, port scans) and can be detected/logged.",
           ar:"الاستطلاع السلبي لا يتفاعل مع الهدف (مثل WHOIS وجوجل). الاستطلاع النشط يلمسه (مثل ping والفحص) ويمكن كشفه وتسجيله." },
    q:{ question:{ en:"Which is ACTIVE reconnaissance?", ar:"أيٌّ منها استطلاع نشط؟" },
        options:[ {en:"Port scanning the target", ar:"فحص منافذ الهدف"},
                  {en:"Reading the company's public website via cache", ar:"قراءة موقع الشركة من الذاكرة المخزنة"},
                  {en:"A WHOIS lookup", ar:"استعلام WHOIS"},
                  {en:"Searching LinkedIn", ar:"البحث في لينكدإن"} ],
        answer:0,
        explain:{ en:"Port scanning sends packets to the target = active and detectable.",
                  ar:"فحص المنافذ يرسل حزمًا إلى الهدف = نشط وقابل للكشف." } } },

  // ---------- PHASE 2: SCANNING & NETWORKING ----------
  { id:"nmap", district:"scan", pos:{x:-52,z:22}, xp:30,
    title:{ en:"Nmap & Port Scanning", ar:"Nmap وفحص المنافذ" },
    tag:{ en:"Tool · Scanning", ar:"أداة · فحص" },
    card:{ en:"Nmap discovers live hosts and open ports, and can fingerprint services and OS. `nmap -sV <ip>` reveals service versions — key for finding vulnerabilities.",
           ar:"يكتشف Nmap الأجهزة الحية والمنافذ المفتوحة، ويحدد الخدمات ونظام التشغيل. الأمر ‎`nmap -sV <ip>`‎ يكشف إصدارات الخدمات — مفتاح إيجاد الثغرات." },
    q:{ question:{ en:"What does `nmap -sV` primarily reveal?", ar:"ماذا يكشف ‎`nmap -sV`‎ بشكل أساسي؟" },
        options:[ {en:"Service/version running on open ports", ar:"الخدمة/الإصدار على المنافذ المفتوحة"},
                  {en:"The admin password", ar:"كلمة مرور المسؤول"},
                  {en:"The target's physical address", ar:"العنوان الفعلي للهدف"},
                  {en:"Nothing useful", ar:"لا شيء مفيد"} ],
        answer:0,
        explain:{ en:"-sV = version detection. Knowing versions lets you match known CVEs.",
                  ar:"‎-sV‎ = كشف الإصدار. معرفة الإصدارات تتيح مطابقة الثغرات المعروفة CVE." } } },
  { id:"ports", district:"scan", pos:{x:-28,z:45}, xp:25,
    title:{ en:"TCP/IP & Common Ports", ar:"TCP/IP والمنافذ الشائعة" },
    tag:{ en:"Networking", ar:"الشبكات" },
    card:{ en:"Ports map to services: 80/443 = HTTP/HTTPS, 22 = SSH, 21 = FTP, 3389 = RDP, 3306 = MySQL. Recognizing them tells you what a host is running.",
           ar:"ترتبط المنافذ بالخدمات: 80/443 = HTTP/HTTPS، 22 = SSH، 21 = FTP، 3389 = RDP، 3306 = MySQL. معرفتها تخبرك بما يشغّله الجهاز." },
    q:{ question:{ en:"Port 443 is normally used for…", ar:"يُستخدم المنفذ 443 عادةً لـ…" },
        options:[ {en:"HTTPS (encrypted web)", ar:"HTTPS (ويب مشفّر)"},
                  {en:"SSH", ar:"SSH"},
                  {en:"FTP", ar:"FTP"},
                  {en:"RDP", ar:"RDP"} ],
        answer:0,
        explain:{ en:"443 = HTTPS. (22=SSH, 21=FTP, 3389=RDP.)",
                  ar:"‏443 = HTTPS. (‏22=SSH، ‏21=FTP، ‏3389=RDP.)" } } },
  { id:"enum", district:"scan", pos:{x:-55,z:52}, xp:25,
    title:{ en:"Enumeration", ar:"التعداد" },
    tag:{ en:"Scanning", ar:"فحص" },
    card:{ en:"Enumeration extracts detailed info from services — usernames, shares, banners, directories. It turns 'a port is open' into 'here's exactly what I can attack'.",
           ar:"يستخرج التعداد معلومات تفصيلية من الخدمات — أسماء المستخدمين والمشاركات واللافتات والمجلدات. يحوّل «المنفذ مفتوح» إلى «هذا بالضبط ما يمكن مهاجمته»." },
    q:{ question:{ en:"The goal of enumeration is to…", ar:"هدف التعداد هو…" },
        options:[ {en:"Extract detailed service info to plan attacks", ar:"استخراج معلومات تفصيلية لتخطيط الهجوم"},
                  {en:"Delete the target's data", ar:"حذف بيانات الهدف"},
                  {en:"Send phishing emails", ar:"إرسال رسائل تصيّد"},
                  {en:"Encrypt the disk", ar:"تشفير القرص"} ],
        answer:0,
        explain:{ en:"Enumeration = deep info-gathering on discovered services.",
                  ar:"التعداد = جمع معلومات عميق عن الخدمات المكتشفة." } } },

  // ---------- PHASE 3: GAINING ACCESS (OWASP + TOOLS) ----------
  { id:"sqli", district:"access", pos:{x:22,z:-30}, xp:35,
    title:{ en:"SQL Injection (OWASP)", ar:"حقن SQL (OWASP)" },
    tag:{ en:"OWASP Top 10 · Web", ar:"OWASP · ويب" },
    card:{ en:"SQL injection sends malicious input that the app puts straight into a database query, letting attackers read or bypass logins. Fix: parameterized queries.",
           ar:"يرسل حقن SQL مدخلات خبيثة تضعها التطبيقات مباشرةً في استعلام قاعدة البيانات، مما يتيح قراءة البيانات أو تجاوز الدخول. الحل: الاستعلامات المُعامَلة." },
    q:{ question:{ en:"Best defense against SQL injection?", ar:"أفضل دفاع ضد حقن SQL؟" },
        options:[ {en:"Parameterized queries / prepared statements", ar:"الاستعلامات المُعامَلة / المُجهّزة"},
                  {en:"Hiding the login page", ar:"إخفاء صفحة الدخول"},
                  {en:"Using a longer password", ar:"استخدام كلمة مرور أطول"},
                  {en:"Disabling JavaScript", ar:"تعطيل جافاسكربت"} ],
        answer:0,
        explain:{ en:"Parameterized queries separate code from data, blocking injection.",
                  ar:"تفصل الاستعلامات المُعامَلة الكود عن البيانات فتمنع الحقن." } } },
  { id:"xss", district:"access", pos:{x:48,z:-18}, xp:30,
    title:{ en:"Cross-Site Scripting (XSS)", ar:"البرمجة عبر المواقع (XSS)" },
    tag:{ en:"OWASP Top 10 · Web", ar:"OWASP · ويب" },
    card:{ en:"XSS injects attacker JavaScript that runs in a victim's browser — stealing sessions or defacing pages. Fix: escape/encode output and use a CSP.",
           ar:"يحقن XSS جافاسكربت المهاجم لتُشغَّل في متصفح الضحية — لسرقة الجلسات أو تشويه الصفحات. الحل: ترميز المخرجات واستخدام CSP." },
    q:{ question:{ en:"XSS runs malicious code where?", ar:"أين يُشغّل XSS الكود الخبيث؟" },
        options:[ {en:"In the victim's browser", ar:"في متصفح الضحية"},
                  {en:"On the database server only", ar:"على خادم قاعدة البيانات فقط"},
                  {en:"Inside the router firmware", ar:"داخل برنامج الراوتر"},
                  {en:"In the printer", ar:"في الطابعة"} ],
        answer:0,
        explain:{ en:"XSS executes in the browser of other users. Encode output to stop it.",
                  ar:"يُنفَّذ XSS في متصفح المستخدمين. رمّز المخرجات لإيقافه." } } },
  { id:"burp", district:"access", pos:{x:30,z:2}, xp:25,
    title:{ en:"Burp Suite", ar:"Burp Suite" },
    tag:{ en:"Tool · Web", ar:"أداة · ويب" },
    card:{ en:"Burp Suite is a proxy that sits between your browser and a web app, letting you intercept, inspect and modify HTTP requests — the core tool for web testing.",
           ar:"‏Burp Suite وكيل يقع بين متصفحك وتطبيق الويب، يتيح اعتراض وفحص وتعديل طلبات HTTP — الأداة الأساسية لاختبار الويب." },
    q:{ question:{ en:"Burp Suite is mainly a…", ar:"‏Burp Suite هو أساسًا…" },
        options:[ {en:"Web proxy to intercept HTTP traffic", ar:"وكيل ويب لاعتراض حركة HTTP"},
                  {en:"Video editor", ar:"محرّر فيديو"},
                  {en:"Password manager", ar:"مدير كلمات مرور"},
                  {en:"Operating system", ar:"نظام تشغيل"} ],
        answer:0,
        explain:{ en:"Burp intercepts and manipulates web requests between client and server.",
                  ar:"يعترض Burp طلبات الويب ويعدّلها بين العميل والخادم." } } },
  { id:"metasploit", district:"access", pos:{x:55,z:-40}, xp:30,
    title:{ en:"Metasploit", ar:"Metasploit" },
    tag:{ en:"Tool · Exploitation", ar:"أداة · استغلال" },
    card:{ en:"Metasploit is an exploitation framework: a library of exploits + payloads you configure and launch against known vulnerabilities to gain a session/shell.",
           ar:"‏Metasploit إطار استغلال: مكتبة من الثغرات والحمولات تُعدّها وتطلقها ضد ثغرات معروفة للحصول على جلسة/طرفية." },
    q:{ question:{ en:"Metasploit is used to…", ar:"يُستخدم Metasploit لـ…" },
        options:[ {en:"Run exploits against known vulnerabilities", ar:"تشغيل استغلالات ضد ثغرات معروفة"},
                  {en:"Design logos", ar:"تصميم الشعارات"},
                  {en:"Back up photos", ar:"نسخ الصور احتياطيًا"},
                  {en:"Write documents", ar:"كتابة المستندات"} ],
        answer:0,
        explain:{ en:"Metasploit packages exploits + payloads for gaining access.",
                  ar:"يجمع Metasploit الاستغلالات والحمولات للحصول على الوصول." } } },
   { id:"bac", district:"access", pos:{x:12,z:-8}, xp:40, lab:"bac",
    title:{ en:"Broken Access Control (OWASP #1)", ar:"التحكم المعطّل بالوصول (OWASP #1)" },
    tag:{ en:"OWASP Top 10 · Hands-on", ar:"OWASP · تطبيقي" },
    card:{ en:"Broken Access Control lets users act outside their permissions — viewing others' data (IDOR) or reaching admin pages directly. It's the #1 web risk. You'll exploit a live example.",
           ar:"يتيح التحكم المعطّل بالوصول للمستخدمين تجاوز صلاحياتهم — رؤية بيانات غيرهم (IDOR) أو الوصول لصفحات الإدارة مباشرةً. إنه الخطر الأول للويب. ستستغل مثالًا حيًا." },
    q:{ question:{ en:"placeholder", ar:"placeholder" }, options:[{en:"a",ar:"a"}], answer:0,
        explain:{ en:"", ar:"" } } },

  // ---------- PHASE 4: MAINTAINING ACCESS ----------
  { id:"privesc", district:"persist", pos:{x:85,z:48}, xp:30,
    title:{ en:"Privilege Escalation", ar:"تصعيد الصلاحيات" },
    tag:{ en:"Post-Exploitation", ar:"ما بعد الاستغلال" },
    card:{ en:"After a foothold, attackers escalate from a normal user to admin/root by abusing misconfigurations, weak permissions or unpatched kernels.",
           ar:"بعد موطئ القدم، يصعّد المهاجم من مستخدم عادي إلى مسؤول/جذر عبر استغلال إعدادات خاطئة أو صلاحيات ضعيفة أو أنوية غير محدّثة." },
    q:{ question:{ en:"Privilege escalation means gaining…", ar:"تصعيد الصلاحيات يعني الحصول على…" },
        options:[ {en:"Higher-level (admin/root) access", ar:"وصول أعلى (مسؤول/جذر)"},
                  {en:"A faster CPU", ar:"معالج أسرع"},
                  {en:"More RAM", ar:"ذاكرة أكبر"},
                  {en:"A new email", ar:"بريد جديد"} ],
        answer:0,
        explain:{ en:"You move from limited user to admin/root to control the system.",
                  ar:"تنتقل من مستخدم محدود إلى مسؤول/جذر للتحكم بالنظام." } } },
  { id:"persistence", district:"persist", pos:{x:108,z:62}, xp:25,
    title:{ en:"Persistence Mechanisms", ar:"آليات الثبات" },
    tag:{ en:"Post-Exploitation", ar:"ما بعد الاستغلال" },
    card:{ en:"Persistence keeps access after reboots — via scheduled tasks, services or new accounts. In a legal test you document these, then help remove them.",
           ar:"يحافظ الثبات على الوصول بعد إعادة التشغيل — عبر المهام المجدولة أو الخدمات أو حسابات جديدة. في اختبار قانوني توثّقها ثم تساعد على إزالتها." },
    q:{ question:{ en:"In an authorized test, backdoors you create should be…", ar:"في اختبار مصرّح به، الأبواب الخلفية التي تنشئها يجب أن…" },
        options:[ {en:"Documented and removed afterward", ar:"تُوثَّق وتُزال لاحقًا"},
                  {en:"Left in place secretly", ar:"تُترك سرًا"},
                  {en:"Sold online", ar:"تُباع عبر الإنترنت"},
                  {en:"Shared publicly", ar:"تُنشر علنًا"} ],
        answer:0,
        explain:{ en:"Ethical testers document everything and clean up all artifacts.",
                  ar:"يوثّق المختبِر الأخلاقي كل شيء وينظّف كل الآثار." } } },

  // ---------- PHASE 5: REPORTING ----------
  { id:"evidence", district:"report", pos:{x:98,z:-90}, xp:25,
    title:{ en:"Findings & Evidence", ar:"النتائج والأدلة" },
    tag:{ en:"Reporting", ar:"التقارير" },
    card:{ en:"A finding needs clear evidence: steps to reproduce, screenshots, affected assets and impact. Without reproducible proof, a vulnerability may be ignored.",
           ar:"تحتاج كل نتيجة إلى دليل واضح: خطوات إعادة الإنتاج، لقطات الشاشة، الأصول المتأثرة، والأثر. بدون دليل قابل للتكرار قد تُتجاهل الثغرة." },
    q:{ question:{ en:"A strong finding always includes…", ar:"النتيجة القوية تتضمن دائمًا…" },
        options:[ {en:"Reproducible steps and evidence", ar:"خطوات قابلة للتكرار ودليلًا"},
                  {en:"Only your opinion", ar:"رأيك فقط"},
                  {en:"The client's passwords in plain text", ar:"كلمات مرور العميل بنص واضح"},
                  {en:"A meme", ar:"صورة طريفة"} ],
        answer:0,
        explain:{ en:"Reproducible steps + evidence make findings credible and fixable.",
                  ar:"الخطوات القابلة للتكرار والدليل تجعل النتائج موثوقة وقابلة للإصلاح." } } },
  { id:"cvss", district:"report", pos:{x:118,z:-78}, xp:30,
    title:{ en:"Risk Rating (CVSS)", ar:"تقييم المخاطر (CVSS)" },
    tag:{ en:"Reporting", ar:"التقارير" },
    card:{ en:"CVSS scores severity 0–10 based on exploitability and impact. It helps clients prioritize: fix the critical 9.8 before the low 3.1.",
           ar:"يقيّم CVSS الخطورة من 0 إلى 10 بناءً على قابلية الاستغلال والأثر. يساعد العميل على الأولوية: أصلح الحرِج 9.8 قبل المنخفض 3.1." },
    q:{ question:{ en:"CVSS is used to…", ar:"يُستخدم CVSS لـ…" },
        options:[ {en:"Rate and prioritize vulnerability severity", ar:"تقييم خطورة الثغرات وترتيب أولوياتها"},
                  {en:"Speed up the network", ar:"تسريع الشبكة"},
                  {en:"Encrypt emails", ar:"تشفير البريد"},
                  {en:"Design the report cover", ar:"تصميم غلاف التقرير"} ],
        answer:0,
        explain:{ en:"CVSS (0–10) standardizes severity so clients fix the worst first.",
                  ar:"يوحّد CVSS (0–10) الخطورة ليصلح العميل الأخطر أولًا." } } },
  { id:"remediation", district:"report", pos:{x:95,z:-70}, xp:25,
    title:{ en:"Remediation & Retest", ar:"الإصلاح وإعادة الاختبار" },
    tag:{ en:"Reporting", ar:"التقارير" },
    card:{ en:"Great reports give actionable fixes, not just problems. After the client patches, you retest to confirm the vulnerability is truly closed.",
           ar:"التقارير الممتازة تقدّم إصلاحات قابلة للتنفيذ لا مشاكل فقط. بعد أن يعالج العميل، تعيد الاختبار للتأكد من إغلاق الثغرة فعلًا." },
    q:{ question:{ en:"Why retest after remediation?", ar:"لماذا نعيد الاختبار بعد الإصلاح؟" },
        options:[ {en:"To confirm the fix actually works", ar:"للتأكد أن الإصلاح يعمل فعلًا"},
                  {en:"To bill more hours only", ar:"لزيادة الفواتير فقط"},
                  {en:"It is never needed", ar:"لا حاجة له أبدًا"},
                  {en:"To delete the report", ar:"لحذف التقرير"} ],
        answer:0,
        explain:{ en:"Retesting verifies the patch closed the hole — the loop isn't done until then.",
                  ar:"تتحقق إعادة الاختبار من أن التصحيح أغلق الثغرة — لا تكتمل الدورة قبلها." } } },
];

export const TOTAL_NODES = NODES.length;
export const MAX_XP = NODES.reduce((s,n)=>s+n.xp,0);
export const nodesOf = (d)=> NODES.filter(n=>n.district===d);
export const districtById = (id)=> DISTRICTS.find(d=>d.id===id);
